name: PR Build Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      worker: ${{ steps.changes.outputs.worker }}
      web: ${{ steps.changes.outputs.web }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/**'
              - 'bun.lock'
            worker:
              - 'apps/worker/**'
              - 'packages/**'
              - 'bun.lock'
            web:
              - 'apps/web/**'
              - 'packages/**'
              - 'bun.lock'
            docs:
              - 'apps/docs/**'
              - 'packages/**'
              - 'bun.lock'

  build-check:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, worker, web, docs]
        include:
          - app: api
            dockerfile: apps/api/Dockerfile
            context: .
          - app: worker
            dockerfile: apps/worker/Dockerfile
            context: .
          - app: web
            dockerfile: apps/web/Dockerfile
            context: .
          - app: docs
            dockerfile: apps/docs/Dockerfile
            context: .
    
    steps:
      - name: Check if app changed
        id: check-changes
        run: |
          if [ "${{ matrix.app }}" = "api" ] && [ "${{ needs.changes.outputs.api }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.app }}" = "worker" ] && [ "${{ needs.changes.outputs.worker }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.app }}" = "web" ] && [ "${{ needs.changes.outputs.web }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.app }}" = "docs" ] && [ "${{ needs.changes.outputs.docs }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        if: steps.check-changes.outputs.skip == 'false'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: steps.check-changes.outputs.skip == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        if: steps.check-changes.outputs.skip == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: false
          tags: relayit-${{ matrix.app }}:pr-${{ github.event.number }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            ${{ matrix.app == 'docs' && 'API_URL=http://localhost:3005' || '' }}
            ${{ matrix.app == 'docs' && 'WEB_URL=http://localhost:3000' || '' }}
            ${{ matrix.app == 'docs' && 'DOCS_URL=http://localhost:3002' || '' }}

      - name: Build success
        if: steps.check-changes.outputs.skip == 'false'
        run: echo "✅ ${{ matrix.app }} build successful" 